### PR TITLE
Upgrade subxt

### PR DESCRIPTION
**Pull request by fewensa**
Update subxt and adapt darwinia

### CODE REVIEW

**Comment by fewensa** [comment]
keep checking: https://github.com/darwinia-network/bridger/issues/185
this branch use [substrate@darwinia-v0.11.3](https://github.com/darwinia-network/substrate/tree/darwinia-v0.11.3)

**Comment by hackfisher** [comment]
@fewensa this version is using jsonrpsee 3.0.0?

**Comment by fewensa** [comment]
It's `0.3.0` not `3.0.0`
Since this commit https://github.com/paritytech/substrate-subxt/commit/2749bd300bd061c1862e1d074f87d7376a5c90d0 (https://github.com/paritytech/substrate-subxt/pull/289), substrate-subxt use jsonrpsee 0.3.0

**Comment by fewensa** [comment]
cargo test will fail.
two reasons:
1. paritytech/substrate-subxt still fail https://github.com/paritytech/substrate-subxt/runs/3399810085
2. the test chain is only support `RuntimeMetadata::V12`, but darwinia is `RuntimeMetadata::V13`
    https://github.com/darwinia-network/substrate-subxt/blob/2846c0d695c8dd806262057aa3cb8a027fd308b3/.github/workflows/rust.yml#L28

we need test use bridger

**Review by hackfisher — APPROVED** [review]

**Comment by hackfisher** [comment]
@fewensa looks like we've merge the changes in current dependency(metadata branch) to this PR?

We'll merge this and then use master as dependency, right?

**Comment by fewensa** [comment]
yes, when merged the bridge darwinia-ethereum will change to master branch.
we will decide on a better solution later, because there are other chains supported, use tag or multiple branch

**Comment by fewensa** [comment]
for issue https://github.com/darwinia-network/bridger/issues/256

**Pull request merged**
